AllCops:
  TargetRubyVersion: 2.3

Style/Documentation:
  Enabled: false

Style/TrivialAccessors:
  AllowDSLWriters: true

Metrics/LineLength:
  Max: 120

Style/FrozenStringLiteralComment:
  Enabled: false
